/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.controlbalanceapi.models.entities.public_.tables.records;


import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balancecontract;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalancecontractRecord extends TableRecordImpl<BalancecontractRecord> implements Record4<Integer, Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = 1696388070;

    /**
     * Setter for <code>PUBLIC.BALANCECONTRACT.BALANCECONTRACTID</code>.
     */
    public void setBalancecontractid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.BALANCECONTRACT.BALANCECONTRACTID</code>.
     */
    public Integer getBalancecontractid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.BALANCECONTRACT.BALANCEID</code>.
     */
    public void setBalanceid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.BALANCECONTRACT.BALANCEID</code>.
     */
    public Integer getBalanceid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.BALANCECONTRACT.EVENTID</code>.
     */
    public void setEventid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.BALANCECONTRACT.EVENTID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.BALANCECONTRACT.BALANCEVALUE</code>.
     */
    public void setBalancevalue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.BALANCECONTRACT.BALANCEVALUE</code>.
     */
    public BigDecimal getBalancevalue() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Balancecontract.BALANCECONTRACT.BALANCECONTRACTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Balancecontract.BALANCECONTRACT.BALANCEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Balancecontract.BALANCECONTRACT.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Balancecontract.BALANCECONTRACT.BALANCEVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBalancecontractid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBalanceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getBalancevalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalancecontractRecord value1(Integer value) {
        setBalancecontractid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalancecontractRecord value2(Integer value) {
        setBalanceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalancecontractRecord value3(Integer value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalancecontractRecord value4(BigDecimal value) {
        setBalancevalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalancecontractRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BalancecontractRecord
     */
    public BalancecontractRecord() {
        super(Balancecontract.BALANCECONTRACT);
    }

    /**
     * Create a detached, initialised BalancecontractRecord
     */
    public BalancecontractRecord(Integer balancecontractid, Integer balanceid, Integer eventid, BigDecimal balancevalue) {
        super(Balancecontract.BALANCECONTRACT);

        set(0, balancecontractid);
        set(1, balanceid);
        set(2, eventid);
        set(3, balancevalue);
    }
}
