/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.controlbalanceapi.models.entities.public_.tables;


import com.cursojunit.controlbalanceapi.models.entities.public_.Keys;
import com.cursojunit.controlbalanceapi.models.entities.public_.Public;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.records.BalancecontractRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Balancecontract extends TableImpl<BalancecontractRecord> {

    private static final long serialVersionUID = -1367461037;

    /**
     * The reference instance of <code>PUBLIC.BALANCECONTRACT</code>
     */
    public static final Balancecontract BALANCECONTRACT = new Balancecontract();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BalancecontractRecord> getRecordType() {
        return BalancecontractRecord.class;
    }

    /**
     * The column <code>PUBLIC.BALANCECONTRACT.BALANCECONTRACTID</code>.
     */
    public final TableField<BalancecontractRecord, Integer> BALANCECONTRACTID = createField("BALANCECONTRACTID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D437C8B2_7442_4E6B_BA1C_64A0A2FAB7F3)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.BALANCECONTRACT.BALANCEID</code>.
     */
    public final TableField<BalancecontractRecord, Integer> BALANCEID = createField("BALANCEID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.BALANCECONTRACT.EVENTID</code>.
     */
    public final TableField<BalancecontractRecord, Integer> EVENTID = createField("EVENTID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.BALANCECONTRACT.BALANCEVALUE</code>.
     */
    public final TableField<BalancecontractRecord, BigDecimal> BALANCEVALUE = createField("BALANCEVALUE", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 2).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.BALANCECONTRACT</code> table reference
     */
    public Balancecontract() {
        this("BALANCECONTRACT", null);
    }

    /**
     * Create an aliased <code>PUBLIC.BALANCECONTRACT</code> table reference
     */
    public Balancecontract(String alias) {
        this(alias, BALANCECONTRACT);
    }

    private Balancecontract(String alias, Table<BalancecontractRecord> aliased) {
        this(alias, aliased, null);
    }

    private Balancecontract(String alias, Table<BalancecontractRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BalancecontractRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BALANCECONTRACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Balancecontract as(String alias) {
        return new Balancecontract(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Balancecontract rename(String name) {
        return new Balancecontract(name, null);
    }
}
