/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.controlbalanceapi.models.entities.public_;


import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balance;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balancecontract;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.records.BalanceRecord;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.records.BalancecontractRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BalanceRecord, Integer> IDENTITY_BALANCE = Identities0.IDENTITY_BALANCE;
    public static final Identity<BalancecontractRecord, Integer> IDENTITY_BALANCECONTRACT = Identities0.IDENTITY_BALANCECONTRACT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BalanceRecord, Integer> IDENTITY_BALANCE = createIdentity(Balance.BALANCE, Balance.BALANCE.BALANCEID);
        public static Identity<BalancecontractRecord, Integer> IDENTITY_BALANCECONTRACT = createIdentity(Balancecontract.BALANCECONTRACT, Balancecontract.BALANCECONTRACT.BALANCECONTRACTID);
    }
}
