/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.controlbalanceapi.models.entities.public_;


import com.cursojunit.controlbalanceapi.models.entities.DefaultCatalog;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balance;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balancecontract;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1584251808;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.BALANCE</code>.
     */
    public final Balance BALANCE = com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balance.BALANCE;

    /**
     * The table <code>PUBLIC.BALANCECONTRACT</code>.
     */
    public final Balancecontract BALANCECONTRACT = com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balancecontract.BALANCECONTRACT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_D437C8B2_7442_4E6B_BA1C_64A0A2FAB7F3,
            Sequences.SYSTEM_SEQUENCE_EFEA157F_6A7A_4887_A677_F87429AC6FE0);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Balance.BALANCE,
            Balancecontract.BALANCECONTRACT);
    }
}
