/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.controlbalanceapi.models.entities.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_D437C8B2_7442_4E6B_BA1C_64A0A2FAB7F3</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_D437C8B2_7442_4E6B_BA1C_64A0A2FAB7F3 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_D437C8B2_7442_4E6B_BA1C_64A0A2FAB7F3", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_EFEA157F_6A7A_4887_A677_F87429AC6FE0</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_EFEA157F_6A7A_4887_A677_F87429AC6FE0 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_EFEA157F_6A7A_4887_A677_F87429AC6FE0", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
