/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.controlbalanceapi.models.entities.public_;


import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balance;
import com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balancecontract;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.BALANCE</code>.
     */
    public static final Balance BALANCE = com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balance.BALANCE;

    /**
     * The table <code>PUBLIC.BALANCECONTRACT</code>.
     */
    public static final Balancecontract BALANCECONTRACT = com.cursojunit.controlbalanceapi.models.entities.public_.tables.Balancecontract.BALANCECONTRACT;
}
